/**
 * `palm completion bash|zsh|fish`: static completion scripts generated from the commander
 * tree (verbs, aliases, utilities, flags per command) and the kind words of each verb.
 */
import type { Command, Option } from 'commander';
import { resourceWords } from '../core/kinds.js';
import { TARGET_IDS } from '../core/types.js';
import type { App } from './app.js';
import { type Invocation, usage, VERBS } from './grammar.js';

export const SHELLS = ['bash', 'zsh', 'fish'] as const;
export type Shell = (typeof SHELLS)[number];

interface OptionModel {
  flags: string[];
  description: string;
  takesValue: boolean;
}

interface CommandModel {
  name: string;
  aliases: string[];
  summary: string;
  options: OptionModel[];
  /** Words for the first argument: kinds (verbs), subcommands, or shells. */
  words: string[];
}

export interface CompletionModel {
  commands: CommandModel[];
  global: OptionModel[];
}

function optionModel(o: Option): OptionModel {
  return {
    flags: [o.short, o.long].filter((f): f is string => Boolean(f)),
    description: o.description,
    takesValue: o.required || o.optional,
  };
}

function firstWords(cmd: Command): string[] {
  const verb = VERBS.find((v) => v.name === cmd.name());
  if (verb) return [...new Set(verb.resources.flatMap((r) => resourceWords(r)))];
  if (cmd.name() === 'completion') return [...SHELLS];
  return cmd.commands.map((c) => c.name());
}

/** The visible command tree as data (hidden aliases and `help` are left out). */
export function completionModel(program: Command): CompletionModel {
  const help = program.createHelp();
  const commands = help
    .visibleCommands(program)
    .filter((c) => c.name() !== 'help')
    .map((c) => ({
      name: c.name(),
      aliases: c.aliases(),
      summary: c.summary() || c.description(),
      options: help.visibleOptions(c).map(optionModel),
      words: firstWords(c),
    }));
  return { commands, global: help.visibleOptions(program).map(optionModel) };
}

const namesOf = (c: CommandModel): string[] => [c.name, ...c.aliases];
const flagsOf = (opts: OptionModel[]): string[] => opts.flatMap((o) => o.flags);
const valueFlags = (m: CompletionModel): string[] =>
  flagsOf([...m.global, ...m.commands.flatMap((c) => c.options)].filter((o) => o.takesValue));

function bashCase(c: CommandModel): string {
  return [
    `    ${namesOf(c).join('|')})`,
    `      opts="${flagsOf(c.options).join(' ')}"`,
    `      words="${c.words.join(' ')}" ;;`,
  ].join('\n');
}

export function bashScript(m: CompletionModel): string {
  const all = m.commands.flatMap(namesOf).join(' ');
  return `# bash completion for palm (generated by: palm completion bash)
_palm() {
  local cur prev cmd="" argc=0 i opts="" words=""
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local global="${flagsOf(m.global).join(' ')}"
  local takes_value=" ${valueFlags(m).join(' ')} "
  case "$prev" in
    -t|--target) COMPREPLY=($(compgen -W "${TARGET_IDS.join(' ')}" -- "$cur")); return ;;
  esac
  for ((i = 1; i < COMP_CWORD; i++)); do
    local w="\${COMP_WORDS[i]}"
    if [[ "$w" == -* ]]; then
      [[ "$takes_value" == *" $w "* ]] && ((i++))
    elif [[ -z "$cmd" ]]; then cmd="$w"
    else ((argc++))
    fi
  done
  if [[ -z "$cmd" ]]; then
    COMPREPLY=($(compgen -W "${all} $global" -- "$cur")); return
  fi
  case "$cmd" in
${m.commands.map(bashCase).join('\n')}
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "$opts $global" -- "$cur"))
  elif ((argc == 0)); then
    COMPREPLY=($(compgen -W "$words" -- "$cur"))
  fi
}
complete -o default -F _palm palm
`;
}

/** A single-quoted zsh/fish word. */
function quote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function zshCase(c: CommandModel): string {
  const opts = flagsOf(c.options).map(quote).join(' ');
  const words = c.words.map(quote).join(' ');
  return `    (${namesOf(c).join('|')}) opts=(${opts}); words=(${words}) ;;`;
}

export function zshScript(m: CompletionModel): string {
  const described = m.commands.flatMap((c) =>
    namesOf(c).map((n) => quote(`${n}:${c.summary.replace(/:/g, ' ')}`)),
  );
  return `#compdef palm
# zsh completion for palm (generated by: palm completion zsh)
_palm() {
  local cmd="" w
  local -i argc=0 i
  local -a commands opts words global takes_value
  commands=(${described.join(' ')})
  global=(${flagsOf(m.global).map(quote).join(' ')})
  takes_value=(${valueFlags(m).map(quote).join(' ')})
  for (( i = 2; i < CURRENT; i++ )); do
    w=\${words[i]}
    if [[ $w == -* ]]; then
      (( \${takes_value[(Ie)$w]} )) && (( i++ ))
    elif [[ -z $cmd ]]; then cmd=$w
    else (( argc++ ))
    fi
  done
  if [[ \${words[CURRENT-1]} == (-t|--target) ]]; then compadd -- ${TARGET_IDS.join(' ')}; return; fi
  if [[ -z $cmd ]]; then
    if [[ $PREFIX == -* ]]; then compadd -- $global; else _describe -t commands 'palm command' commands; fi
    return
  fi
  case $cmd in
${m.commands.map(zshCase).join('\n')}
  esac
  if [[ $PREFIX == -* ]]; then compadd -- $opts $global
  elif (( argc == 0 )); then compadd -- $words
  fi
}
if [[ "\${funcstack[1]}" == "_palm" ]]; then _palm "$@"; else compdef _palm palm; fi
`;
}

function fishOption(o: OptionModel, condition?: string): string {
  const parts = ['complete -c palm'];
  if (condition) parts.push(`-n ${quote(condition)}`);
  for (const f of o.flags) parts.push(f.startsWith('--') ? `-l ${f.slice(2)}` : `-s ${f.slice(1)}`);
  if (o.takesValue) parts.push('-r');
  if (o.flags.includes('--target')) parts.push(`-a ${quote(TARGET_IDS.join(' '))}`);
  parts.push(`-d ${quote(o.description)}`);
  return parts.join(' ');
}

function fishCommand(c: CommandModel): string[] {
  const names = namesOf(c).join(' ');
  const seen = `__fish_seen_subcommand_from ${names}`;
  const lines = namesOf(c).map(
    (n) => `complete -c palm -n '__fish_use_subcommand' -a ${n} -d ${quote(c.summary)}`,
  );
  if (c.words.length)
    lines.push(
      `complete -c palm -n ${quote(`${seen}; and not __fish_seen_subcommand_from ${c.words.join(' ')}`)} -a ${quote(c.words.join(' '))}`,
    );
  for (const o of c.options) lines.push(fishOption(o, seen));
  return lines;
}

export function fishScript(m: CompletionModel): string {
  return `# fish completion for palm (generated by: palm completion fish)
complete -c palm -f
${m.global.map((o) => fishOption(o)).join('\n')}
${m.commands.flatMap(fishCommand).join('\n')}
`;
}

export function completionScript(program: Command, shell: Shell): string {
  const model = completionModel(program);
  if (shell === 'bash') return bashScript(model);
  if (shell === 'zsh') return zshScript(model);
  return fishScript(model);
}

export async function run(inv: Invocation, app: App): Promise<void> {
  const [shell, ...extra] = inv.names;
  if (!shell || extra.length || !(SHELLS as readonly string[]).includes(shell))
    throw usage(`palm completion takes one of: ${SHELLS.join(', ')}`, 'palm completion bash');
  if (!app.program) throw new Error('the command tree is not available');
  const script = completionScript(app.program, shell as Shell);
  if (app.out.jsonMode) app.out.json({ shell, script });
  else app.out.out(script.trimEnd());
}
