"""Build every palm brand asset from one set of numbers.

    python3 brand/tools/build.py            # everything
    python3 brand/tools/build.py variants   # candidates/refined-{1,2,3}.svg + refined-preview.png
    python3 brand/tools/build.py svg        # mark, favicon, wordmarks
    python3 brand/tools/build.py png        # favicons, social card, preview.png

Needs python3 with Pillow, Google Chrome, and JetBrains Mono (only for
re-outlining the wordmark; the committed SVGs need no font).
"""
import math, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from frond import frond_path, fan, extent, outline, centroid

BRAND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAND = os.path.join(BRAND, "candidates")
FONT = os.path.expanduser("~/Library/Fonts/JetBrainsMono-{}.ttf")
GREEN, MINT, INK, PAPER = "#12876A", "#3DD6A3", "#10231E", "#FFFFFF"
GREY = {50: "#F3F6F5", 100: "#E2E8E6", 300: "#B3C1BD", 500: "#63746F", 700: "#3A4B46", 900: "#1B2E29"}

# The grid (64-unit viewBox). Every ray grows from one pivot; leaflet tips and
# the stem end share one terminal radius R.
PIVOT = (32, 35)
LEN, STEM = 25, 21
VARIANTS = {  # label, leaflet angles, leaflet radius at the pivot, terminal radius R, extra length
    1: ("5 leaflets, 32 deg steps", fan(5, 32), 1.25, 3.5, {}),
    2: ("7 leaflets, 24 deg steps", fan(7, 24), 1, 3, {}),
    3: ("7 leaflets, 24 deg steps, centre +3", fan(7, 24), 1, 3, {0: 3}),
}
WINNER = 1


def rays_for(k, scale=1.0):
    _, angles, rb, r, extra = VARIANTS[k]
    return ([(a, (LEN + extra.get(a, 0)) * scale, rb * scale, r * scale) for a in angles]
            + [(180, STEM * scale, r * scale, r * scale)])


def mark_d(k=WINNER, x=None, y=None, height=None):
    """Path data for variant k; optionally scaled to `height` with its bbox at (x, y)."""
    if height is None:
        return frond_path(PIVOT, rays_for(k))
    x0, y0, x1, y1 = extent(PIVOT, rays_for(k))
    s = height / (y1 - y0)
    return frond_path((x + (PIVOT[0] - x0) * s, y + (PIVOT[1] - y0) * s), rays_for(k, s))


def construction(k):
    _, angles, rb, r, extra = VARIANTS[k]
    ang = "0" + "".join(f", ±{a:g}" for a in angles if a > 0)
    c = f" (centre +{extra[0]})" if extra else ""
    return (f"palm mark, generated by tools/build.py. Pivot {PIVOT[0]},{PIVOT[1]}.\n"
            f"       Leaflets at {ang} deg: tapered bars, r{rb:g} at the pivot to r{r:g} at the tip,\n"
            f"       {LEN}{c} from pivot to tip centre. Stem at 180 deg: bar r{r:g}, {STEM} long.")


def write(name, text):
    with open(os.path.join(BRAND, name), "w") as f:
        f.write(text)


def svg_doc(body, viewbox="0 0 64 64", comment=None, attrs=""):
    c = f"  <!-- {comment} -->\n" if comment else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}"{attrs}>\n'
            f"{c}{body}</svg>\n")


# ---------------------------------------------------------------- variants
def variants():
    rows = []
    for k, (label, *_rest) in VARIANTS.items():
        d = mark_d(k)
        write(f"candidates/refined-{k}.svg",
              svg_doc(f'  <path d="{d}"/>\n', comment=construction(k), attrs=' fill="currentColor"'))
        cx, cy, area = centroid(outline(PIVOT, rays_for(k)))
        x0, y0, x1, y1 = extent(PIVOT, rays_for(k))
        print(f"refined-{k}: bbox x {x0:.2f}-{x1:.2f} y {y0:.2f}-{y1:.2f}; centroid {cx:.2f},{cy:.2f}")
        rows.append((f"refined-{k}: {label}", d))
    from sheets import variant_sheet
    variant_sheet(rows, os.path.join(CAND, "refined-preview"))


# ---------------------------------------------------------------- marks
# Favicon viewBox: the mark bbox (6.03-57.97 x 6.5-59.5) in a 56-unit square,
# so at 16/32/48 px the stem edges land exactly on pixel boundaries.
FAVICON_VIEWBOX = "4 5 56 56"


def marks():
    d = mark_d()
    note = construction(WINNER)
    write("mark.svg", svg_doc(f'  <path d="{d}"/>\n', comment=note, attrs=' fill="currentColor"'))
    write("mark-green.svg", svg_doc(f'  <path d="{d}"/>\n', attrs=f' fill="{GREEN}"'))
    write("mark-dark.svg", svg_doc(f'  <path d="{d}"/>\n', attrs=f' fill="{MINT}"'))
    write("favicon.svg", svg_doc(
        f"  <style>path{{fill:{GREEN}}}@media (prefers-color-scheme:dark){{path{{fill:{MINT}}}}}</style>\n"
        f'  <path d="{d}"/>\n', viewbox=FAVICON_VIEWBOX))


# ---------------------------------------------------------------- wordmarks
def glyph_run(text, weight, pen_x, baseline, k):
    """Outline `text` in JetBrains Mono; font units * k, baseline at y=baseline."""
    from ttf import Font, contour_path
    f = Font(FONT.format(weight))
    ds = []
    for i, ch in enumerate(text):
        gid = f.cmap[ord(ch)]
        ox = pen_x + i * f.advance(gid) * k
        tf = lambda x, y, ox=ox: (ox + x * k, baseline - y * k)
        ds += [contour_path(c, tf) for c in f.contours(gid)]
    return "".join(ds), f


def lockup_metrics(weight):
    from ttf import Font
    f = Font(FONT.format(weight))
    glyphs = [f.contours(f.cmap[ord(c)]) for c in "palm"]
    ink_l = min(q[0] for c in glyphs[0] for q in c)
    ink_r = 3 * 600 + max(q[0] for c in glyphs[3] for q in c)
    desc = min(q[1] for c in glyphs[0] for q in c)
    return f, ink_l, ink_r, desc


def mark_geometry():
    x0, y0, x1, y1 = extent(PIVOT, rays_for(WINNER))
    _, angles, rb, r, _ = VARIANTS[WINNER]
    outer = max(angles)
    tip_top = PIVOT[1] - LEN * math.cos(math.radians(outer)) - r
    return x0, y0, x1, y1, tip_top, r


def wordmark(weight="SemiBold", k=0.1):
    """Horizontal lockup, in font units * k. The stem end sits on the baseline,
    the outer leaflet tips touch the x-height, and the gap to the p equals the
    leaflet width (2R) at lockup scale."""
    f, ink_l, ink_r, desc = lockup_metrics(weight)
    x0, y0, x1, y1, tip_top, r = mark_geometry()
    s = f.x_height / (y1 - tip_top)               # font units per mark unit
    mh = (y1 - y0) * s                             # mark height in font units
    top = max(mh, f.cap_height)
    gap = 2 * r * s
    mw = (x1 - x0) * s
    W, H = (mw + gap + ink_r - ink_l) * k, (top - desc) * k
    base = top * k
    md = mark_d(x=0, y=base - mh * k, height=mh * k)
    td, _ = glyph_run("palm", weight, (mw + gap - ink_l) * k, base, k)
    return W, H, md, td, dict(scale=s, gap=gap, mark_top=mh, cap=f.cap_height, xh=f.x_height)


def wordmark_stacked(weight="SemiBold", k=0.1):
    """Stacked lockup: mark twice the cap height, centred on the text's ink box,
    gap to the ascender line equal to the leaflet width at that scale."""
    f, ink_l, ink_r, desc = lockup_metrics(weight)
    x0, y0, x1, y1, tip_top, r = mark_geometry()
    mh = 2 * f.cap_height
    s = mh / (y1 - y0)
    mw = (x1 - x0) * s
    gap = 2 * r * s
    tw = ink_r - ink_l
    W = max(tw, mw)
    H = (mh + gap + f.cap_height - desc)
    md = mark_d(x=(W - mw) / 2 * k, y=0, height=mh * k)
    base = (mh + gap + f.cap_height) * k
    td, _ = glyph_run("palm", weight, ((W - tw) / 2 - ink_l) * k, base, k)
    return W * k, H * k, md, td


def fmt2(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def lockup_svg(W, H, md, td, mark_fill, text_fill, label):
    return svg_doc(f'  <title>{label}</title>\n'
                   f'  <path fill="{mark_fill}" d="{md}"/>\n'
                   f'  <path fill="{text_fill}" d="{td}"/>\n',
                   viewbox=f"0 0 {fmt2(W)} {fmt2(H)}", attrs=' role="img"')


WEIGHT = "SemiBold"


def wordmarks():
    W, H, md, td, info = wordmark(WEIGHT)
    print("lockup:", {k: round(v, 1) for k, v in info.items()}, "viewBox", fmt2(W), fmt2(H))
    write("wordmark.svg", lockup_svg(W, H, md, td, GREEN, INK, "palm"))
    write("wordmark-dark.svg", lockup_svg(W, H, md, td, MINT, PAPER, "palm"))
    W, H, md, td = wordmark_stacked(WEIGHT)
    write("wordmark-stacked.svg", lockup_svg(W, H, md, td, GREEN, INK, "palm"))
    write("wordmark-stacked-dark.svg", lockup_svg(W, H, md, td, MINT, PAPER, "palm"))


# ---------------------------------------------------------------- contrast
def luminance(hex_):
    ch = [int(hex_[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    ch = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in ch]
    return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2]


def contrast(a, b):
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def svg_all():
    marks()
    wordmarks()


def png_all():
    from sheets import pngs
    pngs()


if __name__ == "__main__":
    steps = {"variants": [variants], "svg": [svg_all], "png": [png_all],
             "all": [variants, svg_all, png_all]}
    for step in steps[sys.argv[1] if len(sys.argv) > 1 else "all"]:
        step()
